# Generated by Django 5.0.2 on 2024-02-12 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shared_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('sweet_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared_app.sweettype')),
            ],
        ),
    ]
